# Generated by Django 2.1.7 on 2019-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(help_text='Task unique id', primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Max 280 char description of the task', max_length=280)),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], help_text='Optional priority stamp from 1 to 3', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Marks task completed')),
            ],
        ),
    ]
