version: '2'
services:
  backend1:
    build: ./backend
    expose:
      - "80"
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    environment:
      - NODE_1_ADDRESS=http://backend2:81
      - NODE_2_ADDRESS=http://backend3:82
  web1:
    build: ./frontend
    command: nodemon private/server.js && yarn start
    environment:
      - NODE_ENV=production
      - PORT=8080
      - BACKENDADDRESS=http://backend1:80
    links:
      - backend1
    ports: 
      - "8080:8080"
      - "3000":"3000"
    volumes:
      - /app/node_modules
      - /app/build
      - ./frontend:/app
  backend2:
    build: ./backend
    expose:
      - "81"
    command: python manage.py runserver 0.0.0.0:81
    ports:
      - "81:81"
    environment:
      - NODE_1_ADDRESS=http://backend1:80
      - NODE_2_ADDRESS=http://backend3:82
  web2:
    build: ./frontend
    command: node private/server.js
    environment:
      - NODE_ENV=production
      - PORT=8081
      - BACKENDADDRESS=http://backend2:81
    links:
      - backend2
    ports: 
      - "8081:8081"
      - "3001":"3001"
    volumes:
      - /app/node_modules
      - /app/build
      - ./frontend:/app
  backend3:
    build: ./backend
    expose:
      - "82"
    command: python manage.py runserver 0.0.0.0:82
    ports:
      - "82:82"
    environment:
      - NODE_1_ADDRESS=http://backend1:80
      - NODE_2_ADDRESS=http://backend2:81
  web3:
    build: ./frontend
    command: node private/server.js
    environment:
      - NODE_ENV=production
      - PORT=8082
      - BACKENDADDRESS=http://backend3:82
    links:
      - backend3
    ports:
      - "8082:8082"
      - "3002":"3002"
    volumes:
      - /app/node_modules
      - /app/build
      - ./frontend:/app